language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

cache:
  - apt
  - packages

env:
  TEXMFHOME="test/texmf"

# Follow the instructions in INSTALL.md. We do not install TeXLive because
# we do not compile LaTeX in the tests and we want to keep the speed of
# Travis tests low.
before_install:
  - sudo add-apt-repository -y 'deb [arch=i386] http://cran.rstudio.com/bin/linux/ubuntu trusty/'
  - sudo apt-get update -qq
  - sudo apt-get install build-essential pypy bzip2 libssl-dev libreadline-dev
  - sudo apt-get install pkg-config libcurl4-openssl-dev python-numpy python-matplotlib
  - sudo apt-get install libbz2-dev liblzma-dev libpcre3-dev gfortran
  - sudo apt-get install --allow-unauthenticated r-base r-base-dev r-recommended
  - mkdir -p test/texmf/tex/latex/sparklines
  - curl http://anorien.csc.warwick.ac.uk/mirrors/CTAN/graphics/sparklines/sparklines.sty --output test/texmf/tex/latex/sparklines/sparklines.sty

before-script:
  - R --version

script:
  - ./build.sh
  - ./test/gen_data.py
  - env PYTHONPATH=`pwd` ./test/test.sh
